<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_produk extends CI_Model
{

    public $table = 'tb_produk';
    public $id = 'id_produk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_produk,namaBarang,stok,harga,deskripsi,tgl_stok,gambar');
        $this->datatables->from('tb_produk');
        //add this line for join
        //$this->datatables->join('table2', 'tb_produk.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('produk/read/$1'),'Read')." | ".anchor(site_url('produk/update/$1'),'Update')." | ".anchor(site_url('produk/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_produk');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_produk', $q);
	$this->db->or_like('namaBarang', $q);
	$this->db->or_like('stok', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('tgl_stok', $q);
	$this->db->or_like('gambar', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_produk', $q);
	$this->db->or_like('namaBarang', $q);
	$this->db->or_like('stok', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('tgl_stok', $q);
	$this->db->or_like('gambar', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_produk.php */
/* Location: ./application/models/M_produk.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-15 21:12:31 */
/* http://harviacode.com */